// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CloudWorx;
//
//    var stateManager = StateManager.FromJson(jsonString);

namespace CloudWorx
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StateManager
    {
        [JsonProperty("device_groups")]
        public List<DeviceGroup> DeviceGroups { get; set; }

        [JsonProperty("device_total")]
        public long DeviceTotal { get; set; }

        [JsonProperty("device_active")]
        public long DeviceActive { get; set; }
    }

    public partial class DeviceGroup
    {
        [JsonProperty("device_room")]
        public string DeviceRoom { get; set; }

        [JsonProperty("device_sensors")]
        public List<DeviceSensor> DeviceSensors { get; set; }

        [JsonProperty("device_count")]
        public long DeviceCount { get; set; }
    }

    public partial class DeviceSensor
    {
        [JsonProperty("device_id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long DeviceId { get; set; }

        [JsonProperty("device_name")]
        public string DeviceName { get; set; }

        [JsonProperty("bridge_name")]
        public string BridgeName { get; set; }

        [JsonProperty("device_type")]
        public string DeviceType { get; set; }

        [JsonProperty("device_power")]
        public long DevicePower { get; set; }

        [JsonProperty("device_value")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long DeviceValue { get; set; }

        [JsonProperty("device_state")]
        public bool DeviceState { get; set; }

        [JsonProperty("device_topic")]
        public string DeviceTopic { get; set; }
    }

    public partial class StateManager
    {
        public static StateManager FromJson(string json) => JsonConvert.DeserializeObject<StateManager>(json, CloudWorx.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this StateManager self) => JsonConvert.SerializeObject(self, CloudWorx.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
